### ISSUE TITLE
Umbrella issue for input types

### ISSUE THREAD

**Issue by afucher** [afucher/Inquirer#2]
- [x] Number https://github.com/afucher/Inquirer/commit/7e87ec57422fe69f6f5c6b00520479738af4a86a
- [x] Confirm https://github.com/afucher/Inquirer/commit/c621e490518fe37530d8da842ef2e95184c19d69
- [x] Password https://github.com/afucher/Inquirer/commit/1bc2112f01b3150d980e1a0952ec1a9bda73f6f9

**Comment by afucher** [comment]
Password input still need some more behaviours to be finished, but initial implementation is working.
new issues with bugs will be created to handle these behaviours
